version: '3.4'

services:
  api:
    image: api
    build:
      context: ./client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 9000:9000
  client:
    image: client
    build:
      context: ./api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
